### ISSUE TITLE
How to re-trigger the rendering of the portal ?

### ISSUE THREAD

**Issue by askz** [LinusBorg/portal-vue#78] opened 2017-09-29 12:29 UTC
Hi,

First, thanks for the hard work on this awesome project !

I have (I think) an edge case : 

I'm using the great [Full Calendar](https://fullcalendar.io/), essentially rendered by jQuery.
I use a wrapper around it but it doesn't matter.

The thing is : I have an element .fc-title, rendered at each component rendering, each event drop, each event update etc.
I tried the two target options, one with target-el and the other with a destination portal.

Both are loosing the 'portal' effect when event is re-rendered. Even if I re-rendered the destination portal.
I tried hack the thing with v-if and :disabled but nothing seems to achieve what I want....
This is the source : 
```vue
<portal :disabled="!rendered" v-bind:key="event.id" v-for="event in events"  name="event1" :target-el="'#event'+event.id">
  <div style="" v-b-popover.click="'I am Top'" container="calendar"
              title="Popover!"
              variant="primary">
    {{msg}}
  </div>
</portal>
```

and the destination is rendered at _each_ event rendering (can be called many times, as many as there is events) : 

```javascript
eventRender: function(event, element) {
  self.rendered = false
  element.find('.fc-title').html(`<div class="event-description" id="event${event.id}"></div> `); 
  console.log(`rendered event ${event.id}`)
  self.rendered = true
}
```

Any suggestions are welcome !
Thanks!

**Comment by LinusBorg** [comment] 2017-09-29 12:47
Hi, 

sorry to hear it's not working as expected for you. 

However I have a hard time following what you are tryint to do, some small example in a codepen would be helpful. Just to see the flow that this is following.

**Comment by askz** [comment] 2017-09-29 13:03
Thanks for the fast reply.
I pushed out the full repo because of external dependencies.. 
https://github.com/askz/portal-vue-bug

```terminal
git clone https://github.com/askz/portal-vue-bug.git
cd portal-vue-bug
yarn
yarn run dev
```
Then load the page and try to drag'n'drop any event to see what happens !

**Comment by askz** [comment] 2017-09-29 13:43
If I add a button to toggle rendered boolean, the portal is re-rendered, but I cannot find a way to re-trigger it from code...

**Comment by LinusBorg** [comment] 2017-09-29 13:45
Thanks, I will  have a look, hopefully tomorrow.

**Comment by LinusBorg** [comment] 2017-09-30 12:41
Okay, so I figured it out. 

The problem is that FullCalendar creates new Elements whenever you move an event, for example.

I solved this by creating a fresh PortalTarget on each `eventRender` call. That means we can remove the `target-el` option from the `<portal>`, and instead provide  a `name` prop.

```html
<template>
  <div id="app">
    <full-calendar :config="config"
                   :events="events">
    </full-calendar>
    <!-- <div v-if="rendered"> -->
    <portal v-for="event in events"
            name="event1"
            v-bind:key="event.id"
            :to="`event${event.id}`">
      <div style=""
           v-b-popover.click="'I am Top'"
           container="calendar"
           title="Popover!"
           variant="primary">
        {{msg}}
      </div>
    </portal>
    <!-- </div> -->
  </div>
</template>

<script>
import Vue from 'vue'
import { PortalTarget } from 'portal-vue'

const PortalTargetComp = Vue.extend(PortalTarget)
export default {
  name: 'app',
  components: {
  },
  data() {
    return {
      msg: 'Portal-vue is ok',
      config: {
        eventRender: function(event, element) {
          // element.find('.fc-title').html(`<div class="event-description" id="event${event.id}">Portal-vue not okay :/</div> `); 
          element.find('.fc-title').html(`
          <div class="event-description" id="event${event.id}">
            <div class="portal-mount-point"></div>
          </div> 
          `);
          const mountElement = element.find('.portal-mount-point').get()[0]
          new PortalTargetComp({
            propsData: {
              name: `event${event.id}`,
            },
            el: mountElement
          })
          console.log(`rendered event ${event.id}`)
        }
      },
      events: [
        {
          id: 1,
          title: 'hey 1',
          start: new Date()
        },
        {
          id: 2,
          title: 'hey 2',
          start: new Date()
        }
      ]
    }
  },
}
</script>

**Comment by LinusBorg** [comment] 2017-10-01 19:30
I'll close this as I think it's solved. Please comment if that doesn't fix it for you and I can re-open

**Closed by LinusBorg** 2017-10-01 19:30 UTC
Labels: question

**Comment by askz** [comment] 2017-10-02 09:21
Wow thank you so much !

It works like a charm.

Thank you again!
