### ISSUE TITLE
$refs inside a portal are not available on $nextTick

### ISSUE THREAD

**Issue by bimbiltu** [LinusBorg/portal-vue#118] opened 2018-04-05 18:09 UTC
I'm still seeing the problem described in #23 using version 1.3.0. To reiterate the problem, if I have the following template
```html
<portal to="destination">
    <div v-if="open" ref="content">foo</div>
</portal> 
```

And I run the code:
```js
app.open = true
app.$nextTick(function() {
  console.log(!!this.$refs.open)
});
```
Then im seeing `false` logged in the console. If I add a second `$nextTick` then the ref is populated. The opposite also happens when setting `open = false`, the `$ref` will remain populated until 2 ticks have passed.

jsfiddle of the problem: https://jsfiddle.net/ke9b8j4e/3/ (i inlined portal-vue so youll need to scroll to the bottom of the script section to see the app code)

**Comment by LinusBorg** [comment] 2018-04-05 20:42
Thanks, will look into it. May be related to #73 and/or the recent switch for $nextTick to a macroTask instead of a microTask (which we will likely revert in Vue 2.6).

Please be a bit patient about this, I'm still in the aftermath of moving to a new appartment and don't have much time to work on this lib at the moment. so this can take a couple of weeks.

Thanks!

**Comment by rjgotten** [comment] 2018-04-23 11:17
FYI; I'm seeing the problem with element references missing from `$refs` even without `v-if` being at play.

I'm simply calling a method on a component from inside a click event handler at a time when the component is long present in the DOM already. E.g.

```html
<button @click="this.$refs.my-component.my-method()">
<portal to="destination">
  <my-component ref="my-component" />
</portal>
```

This still fails with `my-component` not being present in `$refs`

**Comment by LinusBorg** [comment] 2018-04-23 11:30
Can you reproduce this on jsfiddle or codesandbox?

**Comment by rjgotten** [comment] 2018-04-23 11:52
Figured it out: there seems to be a problem with destination portals needing to exist _before_ a child component uses them.

In [my example fiddle](https://jsfiddle.net/o81tz8z0/2/) the 'before' portal has a `ref` that can be found, but the after does not.

**Comment by LinusBorg** [comment] 2018-04-23 14:01
Thanks, that's actually a great lead about what may be going on. Unfortunately, it also sounds like that may be a caveat that's not really solvable.

But I'll look into it in the coming weeks.

**Comment by philippkuehn** [comment] 2018-04-26 14:29
Is it possible to emit an event when the portal is mounted? With this I could handle _some_ cases (not all).

```vue
<template>
  <portal @mounted="onMounted">
    <my-component ref="my-component" />
  </portal>
</template>
```

**Comment by saintplay** [comment] 2018-05-15 02:35
Hi @LinusBorg first of all thanks for creating this, it's helping me a lot with a long-time-headache-printing-problem.

I ended up realizing of this issue, I'm not using any `ref` but I need a portal renderization.

When using a `$nextTick`, it seems that portal isn't rendered yet.

So, [using](https://github.com/saintplay/vue-print-demo/blob/master/src/App.vue#L45-L49) a **double** `$nextTick` works, **but is this a workaround reliable**?

I made a demo

- [Repo](https://github.com/saintplay/vue-print-demo)
- [Demo](https://vue-print-demo.now.sh/)

**Comment by talski** [comment] 2019-06-07 01:21
In my case the $refs is not available because of the css animation, I've set the transition to 0.25s, so in order to work properly I've set a timeout to a slightly higher number, in this case 300ms worked.

`setTimeout(() => this.$refs.search.focus(), 300);`

**Comment by danielmorincc** [comment] 2019-11-29 14:57
> In my case the $refs is not available because of the css animation, I've set the transition to 0.25s, so in order to work properly I've set a timeout to a slightly higher number, in this case 300ms worked.
> setTimeout(() => this.$refs.search.focus(), 300);

Thanks, this seems to for me also.  I call this code from a component which is portalled to a component which is shown using v-show (not v-if).  this component has an enter transition when shown.  Seems to be some issue somewhere caused by vue portal, where refs are undefined during these transitions.  I hope this will be resolved in vue v3.

**Comment by deefeloper** [comment] 2020-02-06 12:18
I seem to be running into this issue mostly during development, I think vue tries to recreate the `$refs` property, and when that happens anything inside the portal is not seen as "there" anymore.

I tried caching the refs, but as `$refs` is not reactive that won't work.

As for the issue that a $ref is not available until the next tick is mentioned in the vue docs somewhere I believe.

**Comment by rannooo** [comment] 2020-02-13 12:47
I was having the same issue (v-if inside portal), then "solved" it by using double $nextTick, which worked perfectly in production for a while. Now, while refactoring my code, I discovered that when moving v-if directly to the portal wrapper, I no longer needed the second $nextTick.

**Comment by Garito** [comment] 2020-03-26 19:37
I've been playing myself with this kind of concept trying refs and ids to move the elements and I have riched the same point
If I've understood the issue correctly, the problem has no good solution because it depends on the children being rendered before it moves the element so the more profound is the children tree the worst

The real issue is that the portal has no way to know when the children are ready cause vue itself doesn't provide any good solution (perhaps a recursive event in the vue lifecycle like ready that emits when all the children are ready)

I hope this helps

**Comment by iKlsR** [comment] 2020-06-07 17:03
I think I solved this by changing `v-if="conditional` to `:disabled="conditional`.

**Comment by iKlsR** [comment] 2020-06-07 17:04
I think I solved this by changing `v-if="conditional` to `:disabled="conditional"` on the portal wrapper.

**Comment by iKlsR** [comment] 2020-06-07 17:05
I think I solved this by changing v-if="conditional" to :disabled="conditional" on the portal wrapper.

**Comment by LinusBorg** [comment] 2020-06-21 10:38
I will close this as the nextTick issue is documented and workarounds have been discussed. the caveat itself is unresolvable as far as I can tell.

**Closed** 2020-06-21 10:38 UTC
Labels: Caveat, wontfix
