### ISSUE TITLE
Basic reactivity

### ISSUE THREAD

**Issue by davestewart** [LinusBorg/portal-vue#105] opened 2018-02-06 11:55 UTC
Hey Thorsten,

I altered your Code Pen example to add some basic reactivity.

- https://codepen.io/davestewart/pen/MQeNjr

Should the text in the input not appear in the portal targets?

Did I miss something?

**Comment by LinusBorg** [comment] 2018-02-06 12:57
Apart from the fact that you should not duplicate targets, which doesn't change the behaviour nod your example, though: 

No. No idea what's going on. 

Reactivity works just like that, usually. 

Won't be able to look at it anytime soon either, I'm in the middle of moving. :(

I had a similar issue about half a year back, and I think it was also on codepen, but was not really reproducible for me. Maybe it's some weird codepen-related thing. 

Maybe try and reproduce this locally with the webpack template or something?

**Comment by davestewart** [comment] 2018-02-06 13:01
> I'm in the middle of moving

Ha! Hope it all goes well.

It's no biggie. Thought we might use it on an upcoming project but just a thought right now.

I'll try to find the time later to check it out, just to put your mind at rest

**Comment by LinusBorg** [comment] 2018-02-06 13:05
> How come? Seems like an ideal use case...

You can use a scoped slot for that. Re-using a normal slot would mean  re-usung the same vnodes in multiple places which will easily break the virtual dom. 

That's not specific to then portal, it's also the case if you would use `this.$slots.default` multiple times in your own render function, for example

**Comment by LinusBorg** [comment] 2018-02-06 13:14
Also maybe update to the latest version of vue

**Comment by truefalse10** [comment] 2018-02-26 13:58
I"m running into the same problem with a computed property not being updated in the portal. 
I have a webpack setup with vue@2.1.10

**Comment by LinusBorg** [comment] 2018-02-26 14:29
Well, since that works in the examples and tests, I can't say much about what you say without a reproduction.

**Comment by fenduru** [comment] 2018-04-12 20:39
@LinusBorg the original reproducer clearly reproduces the problem even after updating it to the latest Vue. I believe this is related to https://github.com/vuejs/vue/issues/7856 as the problem does not exist when using scopedSlots.

@davestewart here is an [updated codepen](https://codepen.io/anon/pen/LdopGj) demonstrating the workaround, which is simply to wrap your portal contents in a `<template slot-scope="unusedVar">`.

**Comment by LinusBorg** [comment] 2018-04-17 19:39
@davestewart 

Okay so I took another look and this and dopn't know why I previously said *this*:

> Apart from the fact that you should not duplicate targets, **which doesn't change the behaviour of your example**, though:
*(emphasis mine)*

This was a supid thing to say because of course it's the source of the problem. Portals have the same limitations as normal slots: you should not use the same vnodes in multiple places - that can have unforseen consequences.

Since this is a documented limitation of normal slots, using a scoped slot is not really a workaround (like @fenduru calls it), it's the way to re-use a slot. That's of course not to say that this can't be improved, but like @fenduru rightly points out, this would have to be fixed in Vue.

I will close this issue as we can't do much about this general limitation.

**Closed by LinusBorg** 2018-04-17 19:39 UTC

**Comment by fenduru** [comment] 2018-04-17 20:46
@LinusBorg it is actually not related to the multiple targets. The problem exists even if you delete all but one portal-target. The problem is due to the fact that no reactive getters are hit in the portal target's render function (since slots aren't reactive), so there nothing is triggering a render in the target.

Vue has special handling for rendering when a slots content changes - it calls `$forceUpdate` when it knows it is changing. `portal-vue` could work around this by having something like:

```
updated() {
  this.target.$forceUpdate()
}
```

I've opened a PR with Vue to make slots reactive which would avoid the need for portal to manually proxy the `$forceUpdate` call

**Comment by LinusBorg** [comment] 2018-04-17 22:02
Hm, I can't reproduce what you refer to. 

I removed all but one portal-targetvfrom The initial example and the targets"a content updated correctly when changing the input's value. 

I suspect you refer to something different, but I don't understand what it is.

**Comment by fenduru** [comment] 2018-04-17 22:16
@LinusBorg ah I was modifying the original codepen which was an ancient version of Vue. With Vue latest it does update correctly (my apologies).

There is indeed an [`updated` hook](https://github.com/LinusBorg/portal-vue/blob/develop/src/components/portal.js#L46) that is triggering a render of the portal-target
