### ISSUE TITLE
[2.0.0-beta.0], $attrs is readonly and  $listeners is readonly warnings

### ISSUE THREAD

**Issue by matthewhardern** [LinusBorg/portal-vue#175] opened 2019-01-30 09:37 UTC
Currently running 2.0.0 version, which is the typescript version, have the following warnings being thrown. 

```
vue.runtime.esm.js?f616:601 [Vue warn]: $attrs is readonly.

found in

---> <PortalTarget>
```

and 

```
 $listeners is readonly.

found in

---> <Portal>
```

any ideas what would be causing this?

**Comment by LinusBorg** [comment] 2019-01-30 09:42
Hi, and thanks for providing feeback for the beta.

> have the following warnings being thrown.

When? Where? in what context?

> any ideas what would be causing this?

Not without an answer to the above questions

**Comment by matthewhardern** [comment] 2019-01-30 10:35
the following is what I have:

```
<portal-target name="actions_bar"></portal-target>

<portal to="actions_bar">
      <button @click="createPolicy()" class="capitalize bg-pink rounded text-white px-3 py-2 outline-none focus:outline-none">add policy</button>
</portal>
```

I am running latest version of vue and is project created via vue cli. I have a guess on what it may be, is it because portal-vue is also loading a copy of vue, and there are clashes ?

**Comment by LinusBorg** [comment] 2019-01-30 11:03
IT would be really helpful to see more than a snippet. Runnable code is the only thing that allows me to see what's going on.

The snippet that you shared is obivously supposed to work as it's basically example code copied from the docs.

> is it because portal-vue is also loading a copy of vue, and there are clashes ?

Maybe, hard to say from that snippet. And as I use vue-cli 3 in portal-vue itself to run an example app, I don't think that would happen.

But only runnable code will allow me to answer that.

**Comment by LinusBorg** [comment] 2019-01-30 11:52
Jeez, 2.0 indeed bundles Vue. How the hell did that happen? ^^

**Comment by LinusBorg** [comment] 2019-01-30 18:21
Revert!

Vue is *not* bundled with portal-vue beta, bundlephobia.com just made me think that - but it showed bue as aprt of the bundle size because I still had listed Vue as a `dependency` in package.json.

moving it to a `peerDependency` solved that, and we now have `2.0.0-beta.2`

But I don't think that this is the cause of your issue - or is it? Please update and report back.

If the problem still exists, please provide runnable code that I can investigate.

**Comment by LinusBorg** [comment] 2019-02-08 08:22
I'll close this as resolved / stale.

If you continue to experience this issue please open a new issue with a reproduction, referencing this one.

**Closed by LinusBorg** 2019-02-08 08:22 UTC
Labels: needs reproduction

**Comment by renatodeleao** [comment] 2020-04-29 10:52
@LinusBorg Kind of late to the party but was trying to upgrade a dialog plugin of mine that uses `portal-vue`, to the latest version and started getting these errors. I understand that [aliasing vue version](https://github.com/LinusBorg/portal-vue/issues/201#issuecomment-484525715) should in theory solve it, but i'm not getting any luck with `@vue/cli`.

### Context 

i'm using `@vue/cli` instant prototyping to run a playground for my component and sanity check that is working. Maybe the fact that it needs to be globally installed creates the version issue?

### More context
- [**Source code**](https://github.com/renatodeleao/a11y-vue-dialog/tree/v0.5.0)
- [**CodeSandox**](https://codesandbox.io/s/renderless-a11y-vue-dialog043-portal-vue217-qjjwl?file=/src/App.vue) — sanity check that this is, in fact, related with `@vue/cli` instant prototyping since i don't get any warnings on a "real" env.

Any suggestion for this usecase? I mean, i can live with the warnings at the playground since is mostly for me to play around trying to break stuff, but maybe you can shed some 💡.

Thanks for the package, and for `<Teleport>` ☮️
