### ISSUE TITLE
Changes are not reactive when compiled with vueify

### ISSUE THREAD

**Issue by brad426** [LinusBorg/portal-vue#50] opened 2017-06-07 17:10 UTC
```
<portal-target name="destination"></portal-target>

<portal to="destination">
  <p>test {{dynamicValue}}</p>
</portal>
```

When `dynamicValue` changes, the content is not updated in the `<portal-target>`
Is there currently any way to achieve this, or any plans to support this is future?

**Comment by brad426** [comment] 2017-06-08 09:08
Sorry,

I've just realized that this is working - https://codepen.io/brad426/pen/pwjLRZ I just cant get it to work within my app - Is there a specific version of `vue` that `portal-vue` depends on?

**Comment by LinusBorg** [comment] 2017-06-08 13:02
> Is there a specific version of vue that portal-vue depends on?

No, any version of Vue 2.* should work.

**Comment by brad426** [comment] 2017-06-08 13:52
Hmmm. I have no idea what the issue was.
I completely simplified my app's code to match exactly what I had in this [fiddle](https://codepen.io/brad426/pen/pwjLRZ), **and the <portal> content still wouldn't update**. The only difference would have been how my code got built - I was using the [vue-cli browserify template](https://github.com/vuejs-templates/browserify)

I switched over to the [webpack](https://github.com/vuejs-templates/webpack) template, dropped all my app's code into the new project structure and then all of the `<portal>` stuff starting **working perfectly.**

**Comment by LinusBorg** [comment] 2017-06-08 14:13
Okay that's really weird ...

**Comment by jbjorge** [comment] 2017-07-13 20:22
I've got exactly the same issue.
I have an older project where it works:
**webpack** with **vue@2.1.1** and **portal-vue@^1.0.0-beta.3**
And a new project where reactivity doesn't work through portals:
**browserify** with **vue@2.4.1** and **portal-vue@^1.1.0**

I thought this must have been some issue with vue and certainly not the code-bundler.
I further tested the webpack- and browserify templates from vue-cli and to my surprise reactivity didn't work through portals with browserify. I updated the templates to use the newest version of vue@2.4.1 and vue-loader/vueify as well. Same result.

Really weird indeed. Don't even know where to start digging.

**Comment by jbjorge** [comment] 2017-08-04 12:32
@LinusBorg I've looked through the portal-vue code, but can't find any reason why it works with webpack and not browserify. It seems like the problem lies somewhere in vueify, but before i go down that road - do you have any idea what might be the cause?

**Comment by LinusBorg** [comment] 2017-08-04 12:50
Absolutely none, sorry :(

**Comment by jbjorge** [comment] 2017-08-04 13:18
I've had a look myself; it would need careful comparison between vue-loader/vueify to track down the bug.
Leaving this here for future googlers:
Looks like it will take more time to debug vueify/browserify than to convert our project over to webpack. If you're reading this and have more time at hand than me, and have found and fixed the issue, please let us know.

**Comment by LinusBorg** [comment] 2017-12-17 23:19
Maybe this can be resolved with #73

**Comment by jbjorge** [comment] 2017-12-18 02:19
Feel free to ping me if it gets implemented and I'll test if it solves it :+1:

**Comment by LinusBorg** [comment] 2017-12-18 07:54
Thanks, will do!

**Comment by ja1984** [comment] 2017-12-21 12:24
I have a project build with vue-cli webpack and I seems to have issues with the reactivity as well

**Comment by LinusBorg** [comment] 2017-12-21 12:29
Hey, thanks for reporting that.  can you provide a minimal reproduction of the issues you are seeing? 

Then I can take a look, otherwise I can't say anything.

**Comment by ja1984** [comment] 2017-12-21 12:53
@LinusBorg I will try to create a minimal reproduction later today!

**Comment by LinusBorg** [comment] 2018-01-02 13:36
@ja1984 FYI, 1.3.0-beta.0 is out with the refactored Wormhole class.

If you want to test it: `npm install portal-vue@next`

**Comment by LinusBorg** [comment] 2018-02-09 21:21
@ja1984  any success with the reproduction?

**Comment by LinusBorg** [comment] 2018-04-20 08:51
I'll close this as a wontfix as we don't make any progress here and I'm not familiar with vuetify in any way, never used it.

If someone else wants to contribute, comment and we can reopen.

**Closed** 2018-04-20 08:51 UTC
Labels: bug, docs, help wanted, wontfix
