### ISSUE TITLE
Portal with no content throws an error

### ISSUE THREAD

**Issue by simplesmiler** [LinusBorg/portal-vue#33] opened 2017-05-06 16:30 UTC
Repro: https://jsfiddle.net/14dtfh51/20/

**Comment by LinusBorg** [comment] 2017-05-08 14:49
Thanks!

**Comment by LinusBorg** [comment] 2017-05-08 20:22
Hm, seems I fixed that already a while ago in `dev`. Can't reproduce this.

TO be sure I will push another beta later this week and test it on your fiddle, before hopefully, finally pushing 1.0.0

**Comment by LinusBorg** [comment] 2017-05-11 21:29
fixed in develop branch

**Closed** 2017-05-11 21:30 UTC
Labels: bug
