### ISSUE TITLE
Lost Elements - works in 1.5.0, fails in 1.5.1

### ISSUE THREAD

**Issue by michaelgallaghertw** [LinusBorg/portal-vue#172] opened 2019-01-10 20:17 UTC
The basic premise of my use case is a popup, my attempt to recreate the issue in a jsfiddle is here:
http://jsfiddle.net/mikeapr4/zt65y2mL/

Unfortunately the JSFiddle doesn't exhibit the same problems :( but maybe it could shed some light on what the problem might be.

Key points on the example:
* Target accepts multiples and I have recreated the other transports in case it is part of the problem
* I have a generic Popup component that wraps a Portal, the portal itself is conditional
* The generic Popup also contains a `slot` for a concrete impl
* The generic Popup contains `vue-global-events` which has a "noop" render function. I've recreated the same here (results in a comment in the output).
* The concrete Popup is a component which can re-render once opened, based on the user interacting with it.

So I've been using my current setup without problems with v1.5.0, I upgraded to v1.5.1 and what I observe is that the portal displays the popup the first time, and if I close without causing any concrete popup re-render, the popup opens again and any number of times.

As soon as I cause a re-render within the opened popup, the popup can close after that, but it will not reopen. Debugging the Elements, it appears that the NoopComponent node still appears, that is to say a comment appears and disappears in the target as the popup is toggled.

Sorry for the complex edge case. Considering the single and simple change that occurred in 1.5.1, I thought maybe it might be possible to guess the root cause here, I don't know what it is.

Cheers
Mike

**Comment by LinusBorg** [comment] 2019-01-10 20:35
Sorry to hear that 1.5.1 causes Troy ow in your case. 

Thanks for the fiddle, even if it doesn't exactly demonstrate the problem. I'll take a look but will be travelling at sagging tomorrow till Sunday evening, so give me some time. 

I'll report back.

**Comment by LinusBorg** [comment] 2019-01-10 21:53
So I took a quick look but the example in the fiddle is, as you said, in fact working and it's not really giving me very much to work with.

Since it works with 1.5.0 and the only change to 1.5.1 was that we removed a key on the portal-target's wrapping element (since that forced unnecessary component destroys and re-create when the number of content sources changed), it's probably related to `key` stuff.

You might want to try to add unique `key` properties to the portal's contents

**Comment by michaelgallaghertw** [comment] 2019-01-11 10:31
Thanks for the quick response, I'll add `key` properties in a few places and see if there is any change in behaviour.

**Comment by LinusBorg** [comment] 2019-01-12 14:38
I don't think that reverting the change is an option, since the issue that it fixes is quite serious: stateful components lose their state when a new item is added to a `multiple` target. 

Adding keys like we do here, on the other hand, feels a bit like a workaround, but are an established thing, and even recommend or sometimes necesssary when rendering lists (like `multiple` does in a way).

So i would rather keep this like it is for the moment and take some time to actually debug this and fine out how to solve it.

**Comment by LinusBorg** [comment] 2019-01-14 11:48
@michaelgallaghertw You can't create a reproduction from your latest findings by any chance? Hard to debug something I can't reproduce. :(

**Comment by michaelgallaghertw** [comment] 2019-01-15 10:37
I'll give it another try, but it will be a day or 2.

**Comment by LinusBorg** [comment] 2019-01-28 08:47
I took a look and see the problem. However since it's only happening with 2.5.17, I would assume that it was a problem in Vue core and that [this fix](https://github.com/vuejs/vue/commit/530ca1b2db315fbd0e360807b2031d26665c5d3d) in 2.5.18 solved the problem.

If you agree I would close this as it was resolved upstream

**Comment by michaelgallaghertw** [comment] 2019-01-28 11:09
That makes sense to me, I didn't check to see over what range of versions it fails. I'm keen to avoid any lost time for anyone else. Any easy way to inform users to avoid using portal-vue with 2.5.17? I've actually been using that version since it released without any problems to push me to upgrade, and like I said, it works with portal-vue 1.5.0.

**Comment by LinusBorg** [comment] 2019-01-30 09:57
It worked with <1.5.1 because we unknowingly circumvented the bug in Vue core by having a changing key on the wrapper element.

`1.5.1` removed this key as it caused another, severe bug i portal-vue itself, and Vue solved it's own bug in `2.5.18`

Which explains the effects you are seeing with different versions.

> Any easy way to inform users to avoid using portal-vue with 2.5.17?

Hard to give a good warning as the thing you are experiencing seems to be an edge case affecting Versions prior to 2.5.18, but I'm not even sure how far back.

We could put something in the docs but I wouldn't want it to be cauising more confusion, so it has to be worded carefully.

**Comment by michaelgallaghertw** [comment] 2019-01-30 11:36
I'd suggest for the next release, you add this to the `package.json`:
```
"peerDependencies": {
  "vue": ">= 2.5.18",
},
```
You could also add a note to the release notes, as technically this is a backwards compatibility break.

**Closed** 2019-04-06 15:58 UTC
Labels: Caveat, docs
