### ISSUE TITLE
Multiple transports without order set - element mixup

### ISSUE THREAD

**Issue by michaelgallaghertw** [LinusBorg/portal-vue#152] opened 2018-10-09 14:25 UTC
I have a UI component used 12 times on a page, it is called `NumberSlider`. This component includes in its template a `<portal to="body">...</portal>`, and inside this portal there are some tags with classes and styles derived from component data.

In the root of my app I have `<portal-target name="body" multiple/>`. And when I click on some local element within `NumberSlider`, it should show/hide (note I'm using `visibility` here, not `v-if`) the markup within the portal.

So initially everything seems to work fine, but anomalies occur, when I debugged my component I found that the data was in a given state, but the transported elements weren't showing the correct markup to match.

I also noticed strangely enough that the components that corrupted were always in the same position (1st and 6th), and it wasn't necessarily straight away, I had to toggle them once or twice. When I examined the portal destination markup, I found that 3 changes from the 1st component might causes 3 different portal destination elements to be modified, rather than only the one that relates to the portal source.

I debugged the portal-vue code and found that a working component will send 3 changes in succession and each time the transport will have the same index.

    var currentIndex = this.getTransportIndex(transport)

However the components that don't work right have a new index each time, i.e. the order of the transports for this destination have changed. I haven't investigated much in the portal-vue code, but my understanding is that this transport array shouldn't be modified from the `portal` component.

I have tried to recreate the failure in a JSFiddle without any success, I'm not sure what the criteria for causing it are. I have however been able to fix the problem by specifying the `order` in the `portal` component:

    <portal to="body" :order="_uid">

I figured the parent component's UID would be a handy unique number for the order sort within portal-vue:

      newTransports.sort(function (a, b) {
        return a.order - b.order;
      });

This workaround solves the problem, but it is an issue that is worth at least documenting in case someone else encounters it. If I find the time I'll investigate further and ideally propose a fix.

I am using v1.3.0 of portal-vue and testing in Chrome 69.

**Comment by LinusBorg** [comment] 2018-10-10 06:39
Hi, and thanks for the detailed report, even if you didn't manage to reproduce it in code so far.

My first guess would be that setting `key` attributes on the content that you send through the portal would be a fix as well.

What you are experiencing is probably the same thing as when you have an arrayrendered by `v-for` and you later switch element positions in that array: You will see that the wrong elements are updated / removed etc. if you haven't set unique `key` properties.

So maybe that can be a fix (and something for me to document) until I can figure out if and how it's fixable in the lib itself.

**Comment by michaelgallaghertw** [comment] 2018-10-10 10:14
Yeah, `key` was my first thought too, but it didn't work, just re-tested it there now to be sure.

**Comment by michaelgallaghertw** [comment] 2018-10-10 11:48
Worth mentioning that this also fixes the problem without the need for `order`:

      newTransports.sort(function(a, b) {
        return a.order - b.order || a.from - b.from
      })

But it doesn't seem like the right fix, that array should have reliable ordering, right?

**Comment by michaelgallaghertw** [comment] 2018-10-10 12:07
Here's a JSFiddle with a similar scenario to mine, but as I said, it isn't easy to reproduce in a fiddle, though it happens every single time in my application.

http://jsfiddle.net/52yexjfc/

![screencast 2018-10-10 09-05-00](https://user-images.githubusercontent.com/32100359/46735121-acf36780-cc6b-11e8-952d-5aa188e09159.gif)

**Comment by LinusBorg** [comment] 2018-10-10 14:18
Not sure I see what's wrong in the latest fiddle - for me, the Characters are in order, and all the right ones have their tick values updated after the character...

![grafik](https://user-images.githubusercontent.com/1444526/46742648-d16d3500-cca7-11e8-94f4-c73a6f3402c8.png)

Edit: reproducible in Chrome:

![grafik](https://user-images.githubusercontent.com/1444526/46742768-024d6a00-cca8-11e8-9294-651886bea4e7.png)

Thanks for the repro, will look into it. It's probably because the somple sort method I implemented doesn't do a stabel sort in Chrome ... :/

**Comment by LinusBorg** [comment] 2018-10-10 14:21
Note: I think I never intended for the multiple option to be used without `order`, but I think it should be fixed to work reliably somehow.

**Comment by tmorehouse** [comment] 2018-11-20 03:30
If I recall correctly, Chrome uses different sort algorithms based on the array length.  It flips between merge sort and quicksort, if the array length is like less than 10 (or some small number)

**Comment by tmorehouse** [comment] 2018-11-20 05:37
Here is an example of Chrome mangling the order when there are multiple elements with the same value used as the sort "key":

```js
JSON.stringify(array)
"[{"a":1,"b":1},{"a":1,"b":2},{"a":1,"b":3},{"a":1,"b":4},{"a":1,"b":5},{"a":1,"b":6},{"a":1,"b":7},{"a":1,"b":8},{"a":1,"b":9},{"a":1,"b":10},{"a":1,"b":11},{"a":1,"b":12},{"a":1,"b":13},{"a":1,"b":14},{"a":1,"b":15},{"a":1,"b":16}]"

JSON.stringify(array.sort((x,y) => x.a - y.a))
"[{"a":1,"b":9},{"a":1,"b":1},{"a":1,"b":3},{"a":1,"b":4},{"a":1,"b":5},{"a":1,"b":6},{"a":1,"b":7},
{"a":1,"b":8},{"a":1,"b":2},{"a":1,"b":10},{"a":1,"b":11},{"a":1,"b":12},{"a":1,"b":13},
{"a":1,"b":14},{"a":1,"b":15},{"a":1,"b":16}]"

JSON.stringify(array.sort((x,y) => x.a - y.a))
"[{"a":1,"b":2},{"a":1,"b":9},{"a":1,"b":3},{"a":1,"b":4},{"a":1,"b":5},{"a":1,"b":6},{"a":1,"b":7},
{"a":1,"b":8},{"a":1,"b":1},{"a":1,"b":10},{"a":1,"b":11},{"a":1,"b":12},{"a":1,"b":13},
{"a":1,"b":14},{"a":1,"b":15},{"a":1,"b":16}]"

JSON.stringify(array.sort((x,y) => x.a - y.a))
"[{"a":1,"b":1},{"a":1,"b":2},{"a":1,"b":3},{"a":1,"b":4},{"a":1,"b":5},{"a":1,"b":6},{"a":1,"b":7},
{"a":1,"b":8},{"a":1,"b":9},{"a":1,"b":10},{"a":1,"b":11},{"a":1,"b":12},{"a":1,"b":13},
{"a":1,"b":14},{"a":1,"b":15},{"a":1,"b":16}]"
```

As you can see, it doesn't preserve the order of the elements (the sort key is the `a` property on the array of objects. `b` is a sequential number that we can use for comparison of the returned order.

**Closed** 2018-11-23 13:41 UTC
Labels: browser quirks, bug
